### ISSUE TITLE
Push rejected, failed to compile PHP (composer.json) app

### ISSUE THREAD

**Issue by kovacsa91** [seatgeek/build-artifacts#4]
I have got following error during compile.

> Script error in /tmp/buildpack20160326-160-1njxwfv/bin/compile on or near line 380
> remote:
> remote:  !     Push rejected, failed to compile PHP (composer.json) app

**Comment by josegonzalez** [comment]
Hokay! I finally sat down and tried to figure out whats going on here:

- 4bb9709fb7b0ae9ed780c220678f49fc49df096c: The CHH buildpack is effectively dead, long live the official heroku buildpack.
- 100926ed69e41bda243accfc869bd4bf83ad37fa: Mcrypt now comes with the official buildpack, so we can drop `tuupola/slim-fake-mcrypt`.
- 1111d54e96622a085f1fa6bb55b43f573fbe60db: The official buildpack requires a Procfile pointing at the `public` directory
- dbcf85585ca96708bf06f249e3ef76bd99a09488: There is a bug in the Model where we try to call something via `$this` when it should be called statically.
- a7a4dc1e9e5297aa7be226f8f65a735e4cdcf65a cec01dfb6a71fb9df43306d28f9e8543ac397427: The `ruflin/elastica` package is old and throwing an exception in an odd way.
- 57b9a4ec8229962e25e39faa3d99f6e35f230ef5: General issues with not having insight into thrown exceptions
- e578e5d822eafc2bf3318d3f4e2882f61a7c93e1: Needs the redis extension

Lots of small changes. PHP sure has changed in the 3 years since I wrote this.

Can you try it out now and let me know how it works (or doesn't)?

**Comment by kovacsa91** [comment]
Thanks a lot!
What do you think, what can causes error message, like this?

> Slim Application Error
> 
> The application could not run because of the following error:
> Details
> Type: Github\Exception\RuntimeException
> Code: 404
> Message: Not Found
> File: /app/vendor/knplabs/github-api/lib/Github/HttpClient/HttpClient.php
> Line: 145

**Comment by josegonzalez** [comment]
You need to add `repo` perms to that token you created.

**Comment by kovacsa91** [comment]
Thanks, that is great!
